TEAM_STATS_URL = 'http://stats.nba.com/stats/leaguedashteamstats?'

TEAM_PARAMETERS = {
	'Conference': '',
	'DateFrom': '',
	'DateTo': '',
	'Division': '',
	'GameScope': '',
	'GameSegment': '',
	'LastNGames': 0,
	'LeagueID': "00",
	'Location': '',
	'MeasureType': "Advanced",
	'Month': 0,
	'OpponentTeamID': 0,
	'Outcome': '',
	'PORound': 0,
	'PaceAdjust': "N",
	'PerMode': "PerGame",
	'Period': 0,
	'PlayerExperience': '',
	'PlayerPosition': '',
	'PlusMinus': "N",
	'Rank': "N",
	'Season': "2018-19",
	'SeasonSegment': '',
	'SeasonType': "Regular Season",
	'ShotClockRange': '',
	'StarterBench': '',
	'TeamID': 0,
	'VsConference': '',
	'VsDivision': '',
}

OFFENSIVE_TEAM_RATINGS_FILE = 'oteam_ratings.txt'
DEFENSIVE_TEAM_RATINGS_FILE = 'dteam_ratings.txt'

REQUEST_HEADERS = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'en-US,en;q=0.8',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
}

TEAM_INDEX = 1
OFFENSIVE_RATING_INDEX = 8
DEFENSIVE_RATING_INDEX = 10

TEAMS = [
	"Boston Celtics",
	"Brooklyn Nets",
	"New York Knicks",
	"Philadelphia 76ers",
	"Toronto Raptors",
	"Chicago Bulls",
	"Cleveland Cavaliers",
	"Detroit Pistons",
	"Indiana Pacers",
	"Milwaukee Bucks",
	"Atlanta Hawks",
	"Charlotte Hornets",
	"Miami Heat",
	"Orlando Magic",
	"Washington Wizards",
	"Denver Nuggets",
	"Minnesota Timberwolves",
	"Oklahoma City Thunder",
	"Portland Trail Blazers",
	"Utah Jazz",
	"Golden State Warriors",
	"LA Clippers",
	"Los Angeles Lakers",
	"Phoenix Suns",
	"Sacramento Kings",
	"Dallas Mavericks",
	"Houston Rockets",
	"Memphis Grizzlies",
	"New Orleans Pelicans",
	"San Antonio Spurs"
]

TEAMNAME_MAP = {
	"ATL":	"Atlanta Hawks",
	"BKN":	"Brooklyn Nets",
	"BOS":	"Boston Celtics",
	"CHA":	"Charlotte Hornets",
	"CHI":	"Chicago Bulls",
	"CLE":	"Cleveland Cavaliers",
	"DAL":	"Dallas Mavericks",
	"DEN":	"Denver Nuggets",
	"DET":	"Detroit Pistons",
	"GSW":	"Golden State Warriors",
	"HOU":	"Houston Rockets",
	"IND":	"Indiana Pacers",
	"LAC":	"LA Clippers",
	"LAL":	"Los Angeles Lakers",
	"MEM":	"Memphis Grizzlies",
	"MIA":	"Miami Heat",
	"MIL":	"Milwaukee Bucks",
	"MIN":	"Minnesota Timberwolves",
	"NOP":	"New Orleans Pelicans",
	"NYK":	"New York Knicks",
	"OKC":	"Oklahoma City Thunder",
	"ORL":	"Orlando Magic",
	"PHI":	"Philadelphia 76ers",
	"PHX":	"Phoenix Suns",
	"POR":	"Portland Trail Blazers",
	"SAC":	"Sacramento Kings",
	"SAS":	"San Antonio Spurs",
	"TOR":	"Toronto Raptors",
	"UTA":	"Utah Jazz",
	"WAS":	"Washington Wizards",
}

TEAMID_MAP = {
	"Boston Celtics": 1610612738,
	"Brooklyn Nets": 1610612751,
	"New York Knicks": 1610612752,
	"Philadelphia 76ers": 1610612755,
	"Toronto Raptors": 1610612761,
	"Chicago Bulls": 1610612741,
	"Cleveland Cavaliers": 1610612739,
	"Detroit Pistons": 1610612765,
	"Indiana Pacers": 1610612754,
	"Milwaukee Bucks": 1610612749,
	"Atlanta Hawks": 1610612737,
	"Charlotte Hornets": 1610612766,
	"Miami Heat": 1610612748,
	"Orlando Magic": 1610612753,
	"Washington Wizards": 1610612764,
	"Denver Nuggets": 1610612743,
	"Minnesota Timberwolves": 1610612750,
	"Oklahoma City Thunder": 1610612760,
	"Portland Trail Blazers": 1610612757,
	"Utah Jazz": 1610612762,
	"Golden State Warriors": 1610612744,
	"LA Clippers": 1610612746,
	"Los Angeles Lakers": 1610612747,
	"Phoenix Suns": 1610612756,
	"Sacramento Kings": 1610612758,
	"Dallas Mavericks": 1610612742,
	"Houston Rockets": 1610612745,
	"Memphis Grizzlies": 1610612763,
	"New Orleans Pelicans": 1610612740,
	"San Antonio Spurs": 1610612759
}
